"""Streamlit dashboard for the Cordilla account-scoring agent.

Run from the repo root with:
    streamlit run agent/ui/app.py

Reads agent/output/worklist.csv and monitoring/latest_report.json (both written by
`python -m agent.run`), and includes a button to re-run the agent from inside the UI.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from agent.graph import MONITORING_REPORT_PATH, WORKLIST_PATH, build_graph  # noqa: E402
from agent.llm.client import get_drafter  # noqa: E402

st.set_page_config(page_title="Cordilla Account Worklist", layout="wide")

STATUS_LABEL = {"pass": "OK", "warn": "WARN", "fail": "FAIL", "not_runnable": "N/A"}


@st.cache_data(show_spinner=False)
def load_worklist(_mtime: float) -> pd.DataFrame:
    return pd.read_csv(WORKLIST_PATH)


@st.cache_data(show_spinner=False)
def load_report(_mtime: float) -> dict:
    with open(MONITORING_REPORT_PATH) as f:
        return json.load(f)


def run_agent() -> None:
    with st.spinner("Running agent..."):
        result = build_graph().invoke({})
    if result.get("abort_reason"):
        st.error(f"Run aborted: {result['abort_reason']}")
    else:
        st.success(f"Scored {len(result['worklist'])} accounts.")
    load_worklist.clear()
    load_report.clear()


st.title("Cordilla Account Worklist")
st.caption(
    "SDR cold-outbound and Account Manager win-back priorities, generated by the scoring agent."
)

if st.button("Run agent now", type="primary"):
    run_agent()

if not WORKLIST_PATH.exists():
    st.warning("No worklist yet — click 'Run agent now' or run `python -m agent.run` first.")
    st.stop()

worklist_mtime = WORKLIST_PATH.stat().st_mtime
report_mtime = MONITORING_REPORT_PATH.stat().st_mtime if MONITORING_REPORT_PATH.exists() else 0

df = load_worklist(worklist_mtime)
report = load_report(report_mtime) if MONITORING_REPORT_PATH.exists() else {}

tab_worklist, tab_monitoring = st.tabs(["Worklist", "Monitoring"])

with tab_worklist:
    st.sidebar.header("Filters")
    tracks = st.sidebar.multiselect(
        "Track", sorted(df["track"].unique()), default=list(df["track"].unique())
    )
    tiers = st.sidebar.multiselect("Tier", ["Hot", "Warm", "Cold"], default=["Hot", "Warm", "Cold"])
    account_types = st.sidebar.multiselect(
        "Account type",
        sorted(df["account_type"].unique()),
        default=list(df["account_type"].unique()),
    )
    review_only = st.sidebar.checkbox("Needs review only", value=False)

    filtered = df[
        df["track"].isin(tracks) & df["tier"].isin(tiers) & df["account_type"].isin(account_types)
    ]
    if review_only:
        filtered = filtered[filtered["needs_review"]]

    st.write(f"{len(filtered)} of {len(df)} accounts")
    st.dataframe(
        filtered[
            [
                "account_id",
                "account_type",
                "track",
                "tier",
                "probability",
                "industry",
                "employee_count",
                "needs_review",
                "reason_codes",
            ]
        ],
        width="stretch",
        hide_index=True,
    )

    st.subheader("Account detail")
    if filtered.empty:
        st.caption("No accounts match the current filters.")
    else:
        selected = st.selectbox("Select an account", filtered["account_id"].tolist())
        row = df[df["account_id"] == selected].iloc[0]
        c1, c2 = st.columns(2)
        with c1:
            st.markdown(f"**{row['account_id']}** — {row['account_type']} — {row['industry']}")
            st.markdown(
                f"Track: `{row['track']}`  |  Tier: `{row['tier']}`  |  "
                f"P(convert): `{row['probability']:.1%}`"
            )
            if row["needs_review"]:
                st.warning(f"Needs review: {row['quality_flags']}")
            st.markdown("**Why:**")
            for bullet in str(row["reason_codes"]).split("; "):
                st.markdown(f"- {bullet}")
        with c2:
            st.markdown("**Draft outreach**")
            draft = row["draft_outreach"] if isinstance(row["draft_outreach"], str) else ""
            if draft:
                st.info(draft)
            else:
                st.caption("No draft generated automatically (Hot tier only, top 20 by probability).")
            if st.button(f"Regenerate draft for {selected}"):
                drafter = get_drafter()
                reason_list = str(row["reason_codes"]).split("; ")
                new_draft = drafter.draft(row.to_dict(), reason_list)
                st.info(new_draft)
                st.caption(f"Backend: {type(drafter).__name__}")

with tab_monitoring:
    st.subheader("Monitoring report")
    if not report:
        st.info("No monitoring report yet — run the agent first.")
    else:
        st.caption(f"Generated at {report.get('generated_at', 'unknown')}")
        for name, result in report.items():
            if name == "generated_at" or not isinstance(result, dict):
                continue
            status = result.get("status", "unknown")
            label = f"{name.replace('_', ' ').title()}: {STATUS_LABEL.get(status, status)}"
            if status == "pass":
                st.success(label)
            elif status == "warn":
                st.warning(label)
            elif status == "fail":
                st.error(label)
            else:
                st.info(label)
            with st.expander("Details"):
                st.json(result)
