"""Streamlit dashboard for the Cordilla account-scoring agent.

Run from the repo root with:
    streamlit run agent/ui/app.py

Reads agent/output/worklist.csv and monitoring/latest_report.json (both written by
`python -m agent.run`), and includes a button to re-run the agent from inside the UI.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from agent.graph import MONITORING_REPORT_PATH, WORKLIST_PATH, build_graph  # noqa: E402
from agent.llm.client import get_drafter  # noqa: E402

st.set_page_config(page_title="Cordilla Account Worklist", layout="wide")

STATUS_LABEL = {"pass": "OK", "warn": "WARN", "fail": "FAIL", "not_runnable": "N/A"}

# Short persona/term glossary shown in the sidebar — full detail lives in
# DOMAIN-DICTIONARY.md, this is just enough to read the table without guessing.
GLOSSARY = {
    "Prospect": "A potential customer who's shown some interest or fits our target profile, but hasn't bought yet.",
    "Suspect": "A company that *might* be a fit, but hasn't been qualified at all yet — least information of the three.",
    "Former Customer": "Used to pay us, doesn't anymore. A win-back target, not a cold lead.",
    "SDR (Sales Development Rep)": "The person who does first-touch cold outreach into Prospects/Suspects.",
    "Account Manager (AM)": "Owns the relationship with existing/former customers — handles win-back here.",
    "Tier (Hot/Warm/Cold)": "How this account ranks against the others in today's batch (top 10% = Hot). Not an absolute score.",
    "Track": "Which persona should work this account — SDR_Outbound or AM_WinBack — based on account type.",
    "needs_review": "The agent isn't fully confident in this row's data (e.g. very old snapshot) — a person should sanity-check it before acting.",
    "Reason codes": "Plain-English signals explaining why the model rated this account the way it did — not a guarantee, just the model's biggest inputs.",
    "Draft outreach": "A starting point for a first message — always read and personalize before sending.",
}


@st.cache_data(show_spinner=False)
def load_worklist(_mtime: float) -> pd.DataFrame:
    return pd.read_csv(WORKLIST_PATH)


@st.cache_data(show_spinner=False)
def load_report(_mtime: float) -> dict:
    with open(MONITORING_REPORT_PATH) as f:
        return json.load(f)


def run_agent() -> None:
    with st.spinner("Running agent..."):
        result = build_graph().invoke({})
    if result.get("abort_reason"):
        st.error(f"Run aborted: {result['abort_reason']}")
    else:
        st.success(f"Scored {len(result['worklist'])} accounts.")
    load_worklist.clear()
    load_report.clear()


st.title("Cordilla Account Worklist")
st.caption(
    "SDR cold-outbound and Account Manager win-back priorities, generated by the scoring agent."
)

if st.button("Run agent now", type="primary"):
    run_agent()

if not WORKLIST_PATH.exists():
    st.warning("No worklist yet — click 'Run agent now' or run `python -m agent.run` first.")
    st.stop()

worklist_mtime = WORKLIST_PATH.stat().st_mtime
report_mtime = MONITORING_REPORT_PATH.stat().st_mtime if MONITORING_REPORT_PATH.exists() else 0

df = load_worklist(worklist_mtime)
report = load_report(report_mtime) if MONITORING_REPORT_PATH.exists() else {}

with st.sidebar.expander("What do these terms mean?"):
    for term, definition in GLOSSARY.items():
        st.markdown(f"**{term}** — {definition}")
    st.caption("Full reference: DOMAIN-DICTIONARY.md")

tab_worklist, tab_monitoring, tab_ask = st.tabs(["Worklist", "Monitoring", "Ask"])

with tab_worklist:
    st.sidebar.header("Filters")
    tracks = st.sidebar.multiselect(
        "Track", sorted(df["track"].unique()), default=list(df["track"].unique())
    )
    tiers = st.sidebar.multiselect("Tier", ["Hot", "Warm", "Cold"], default=["Hot", "Warm", "Cold"])
    account_types = st.sidebar.multiselect(
        "Account type",
        sorted(df["account_type"].unique()),
        default=list(df["account_type"].unique()),
    )
    review_only = st.sidebar.checkbox("Needs review only", value=False)

    filtered = df[
        df["track"].isin(tracks) & df["tier"].isin(tiers) & df["account_type"].isin(account_types)
    ]
    if review_only:
        filtered = filtered[filtered["needs_review"]]

    st.write(f"{len(filtered)} of {len(df)} accounts")
    st.dataframe(
        filtered[
            [
                "account_id",
                "account_type",
                "track",
                "tier",
                "probability",
                "industry",
                "employee_count",
                "needs_review",
                "reason_codes",
            ]
        ],
        width="stretch",
        hide_index=True,
    )

    st.subheader("Account detail")
    if filtered.empty:
        st.caption("No accounts match the current filters.")
    else:
        selected = st.selectbox("Select an account", filtered["account_id"].tolist())
        row = df[df["account_id"] == selected].iloc[0]
        c1, c2 = st.columns(2)
        with c1:
            st.markdown(f"**{row['account_id']}** — {row['account_type']} — {row['industry']}")
            st.markdown(
                f"Track: `{row['track']}`  |  Tier: `{row['tier']}`  |  "
                f"P(convert): `{row['probability']:.1%}`"
            )
            if row["needs_review"]:
                st.warning(f"Needs review: {row['quality_flags']}")
            st.markdown("**Why:**")
            for bullet in str(row["reason_codes"]).split("; "):
                st.markdown(f"- {bullet}")
        with c2:
            st.markdown("**Draft outreach**")
            draft = row["draft_outreach"] if isinstance(row["draft_outreach"], str) else ""
            if draft:
                st.info(draft)
            else:
                st.caption("No draft generated automatically (Hot tier only, top 20 by probability).")
            if st.button(f"Regenerate draft for {selected}"):
                drafter = get_drafter()
                reason_list = str(row["reason_codes"]).split("; ")
                new_draft = drafter.draft(row.to_dict(), reason_list)
                st.info(new_draft)
                st.caption(f"Backend: {type(drafter).__name__}")

with tab_monitoring:
    st.subheader("Monitoring report")
    if not report:
        st.info("No monitoring report yet — run the agent first.")
    else:
        st.caption(f"Generated at {report.get('generated_at', 'unknown')}")
        for name, result in report.items():
            if name == "generated_at" or not isinstance(result, dict):
                continue
            status = result.get("status", "unknown")
            label = f"{name.replace('_', ' ').title()}: {STATUS_LABEL.get(status, status)}"
            if status == "pass":
                st.success(label)
            elif status == "warn":
                st.warning(label)
            elif status == "fail":
                st.error(label)
            else:
                st.info(label)
            with st.expander("Details"):
                st.json(result)

with tab_ask:
    st.subheader("Ask about an account or a term")
    st.caption(
        "Answers are grounded in DOMAIN-DICTIONARY.md and the worklist data — mention an "
        "account ID (e.g. ACC-00533) to ask about a specific account. Requires GROQ_API_KEY "
        "in a local .env file."
    )

    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    for role, content in st.session_state.chat_history:
        with st.chat_message(role):
            st.markdown(content)

    question = st.chat_input("e.g. Why is ACC-00533 a Hot account?")
    if question:
        st.session_state.chat_history.append(("user", question))
        with st.chat_message("user"):
            st.markdown(question)
        with st.chat_message("assistant"):
            try:
                from agent.chatbot import ask

                answer = st.write_stream(ask(question))
            except Exception as exc:  # noqa: BLE001 - surface any failure directly in the UI
                answer = f"Couldn't reach the assistant: {exc}"
                st.error(answer)
        st.session_state.chat_history.append(("assistant", answer))
